# Generated by Django 5.1.6 on 2026-02-22 08:56

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(max_length=100, verbose_name='Pipeline')),
                ('params_json', models.JSONField(blank=True, default=dict, verbose_name='Параметри')),
                ('status', models.CharField(choices=[('queued', 'На опашка'), ('running', 'Изпълнява се'), ('done', 'Завършен'), ('failed', 'Неуспешен')], default='queued', max_length=20, verbose_name='Статус')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогрес (%)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Стартиран на')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завършен на')),
                ('error_message', models.TextField(blank=True, verbose_name='Съобщение за грешка')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Стартиран от')),
            ],
            options={
                'verbose_name': 'Задача за анализ',
                'verbose_name_plural': 'Задачи за анализ',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('overlay', 'Overlay'), ('metrics', 'Метрики'), ('report', 'Отчет'), ('preview', 'Преглед')], max_length=20, verbose_name='Вид')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.artifact_upload_to, verbose_name='Файл')),
                ('data_json', models.JSONField(blank=True, default=dict, verbose_name='Данни (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.analysisjob', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Артефакт',
                'verbose_name_plural': 'Артефакти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Чернова'), ('in_review', 'В преглед'), ('final', 'Финален')], default='draft', max_length=20, verbose_name='Статус')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Тагове')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновен на')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Създаден от')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсове',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='core.case', verbose_name='Кейс'),
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Писан на')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.case', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментари',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен')),
                ('role', models.CharField(choices=[('viewer', 'Наблюдател'), ('editor', 'Редактор')], default='viewer', max_length=10, verbose_name='Роля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Изтича на')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. използвания')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name='Брой използвания')),
                ('revoked', models.BooleanField(default=False, verbose_name='Отменен')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='core.case', verbose_name='Кейс')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL, verbose_name='Създаден от')),
            ],
            options={
                'verbose_name': 'Споделен линк',
                'verbose_name_plural': 'Споделени линкове',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Изображение')], max_length=10, verbose_name='Тип')),
                ('original_file', models.FileField(upload_to=core.models.evidence_upload_to, verbose_name='Оригинален файл')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Качен на')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='Метаданни')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='core.case', verbose_name='Кейс')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL, verbose_name='Качен от')),
            ],
            options={
                'verbose_name': 'Доказателство',
                'verbose_name_plural': 'Доказателства',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='core.evidence', verbose_name='Доказателство'),
        ),
        migrations.CreateModel(
            name='EvidencePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index', models.PositiveIntegerField(verbose_name='Индекс на страница')),
                ('rendered_image', models.ImageField(upload_to=core.models.page_image_upload_to, verbose_name='Рендерирано изображение')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Ширина (px)')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Височина (px)')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.evidence', verbose_name='Доказателство')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страници',
                'ordering': ['evidence', 'page_index'],
                'unique_together': {('evidence', 'page_index')},
            },
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_jobs', to='core.evidencepage', verbose_name='Страница'),
        ),
        migrations.CreateModel(
            name='CaseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Наблюдател'), ('editor', 'Редактор')], default='viewer', max_length=10, verbose_name='Роля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавен на')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.case', verbose_name='Кейс')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Поканен от')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Потребител')),
            ],
            options={
                'verbose_name': 'Членство в кейс',
                'verbose_name_plural': 'Членства в кейсове',
                'unique_together': {('case', 'user')},
            },
        ),
    ]
