# Generated by Django 5.1.6 on 2026-02-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Тагове'),
        ),
    ]
