# Generated by Django 5.1.6 on 2026-02-22 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('target_type', models.CharField(blank=True, max_length=100, verbose_name='Тип обект')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='ID на обект')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час')),
                ('details_json', models.JSONField(blank=True, default=dict, verbose_name='Детайли')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Актьор')),
            ],
            options={
                'verbose_name': 'Одит запис',
                'verbose_name_plural': 'Одит записи',
                'ordering': ['-timestamp'],
            },
        ),
    ]
